### ISSUE TITLE
Command Line Interface (CLI)

### ISSUE THREAD

**Issue by Mackignacio** [Mackignacio/maya#2]
## 📝 Description
It will be a nice feature if we can generate the basic files and file structure with just a single command on the terminal. The solution is create a CLI that generates these files. It will great if we can have a custom command that follows this pattern ` maya <action> <file-type> <directory>`.

## 📋 Todo:
Propose commands
- [ ] `maya new` -> Create new project and generates basic files and structures.
- [ ] `maya add <file-type> <directory>` -> This will add a file on the project. 
- [ ] `maya add controller <directory>` -> This will add a controller on the directory specified. 
- [ ] `maya add model <directory>` -> This will add a model on the directory specified. 
- [ ] `maya add router <directory>` -> This will add a model on the directory specified. 

## 🔍 Additional Info

These commands can be updated if needed.
